# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

container:
  image: sysdiglabs/secure-inline-scan:2
  options: -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock

variables:
  containerRegistryConnection: containerRegistry
  imageName: 'sysdiglabs/dummy-vuln-app'
  tags: latest

steps:
- task: Docker@2
  displayName: Build image
  inputs:
    repository: $(imageName)
    command: build
    tags: $(tags)

- script: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/sysdig/secure-inline-scan:2 -k $(secureApiKey) {imageName}:{tag} --storage-type docker-daemon --storage-path /var/run/docker.sock
  displayName: Scan image

