# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

container:
  image: sysdiglabs/secure-inline-scan:2
  options: -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock

variables:
  containerRegistryConnection: containerRegistry
  imageName: 'sysdiglabs/dummy-vuln-app'
  tags: |
    latest

steps:
- task: Docker@2
  displayName: Build image
  inputs:
    repository: $(imageName)
    command: build
    tags: $(tags)

- script: inline_scan analyze -s https://secure.sysdig.com -k $(secureApiKey) $(imageName):latest
  displayName: Scan image
- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: $(containerRegistryConnection)
- task: Docker@2
  inputs:
    command: 'push'
    tags: $(tags)
    containerRegistry: $(containerRegistryConnection)
